
#!/bin/bash
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cp="cp -i"
alias d="ls"
alias df="df -h -x supermount"
alias du="du -h"
alias egrep="egrep --color"
alias fgrep="fgrep --color"
alias grep="grep --color"
alias l="ls"
alias la="ls -a"
alias ll="ls -l"
alias ls="ls -F --color=auto"
alias lsd="ls -d */"
alias md="mkdir"
alias mv="mv -i"
alias p="cd -"
alias rd="rmdir"
alias rm="rm -i"
alias install="sudo apt-get install"
alias gpush="git push"
alias gpull="git pull"
alias gcommit="git commit -am"
alias greset="git reset --hard origin/master"
alias addrep="sudo add-apt-repository"
alias update="sudo apt-get update"
alias remove="sudo apt-get remove"
alias fontcache="fc-cache -f -v"
alias dinstall="sudo dpkg -i"
alias reboot="sudo reboot"
alias er="ember g route"
alias ec="ember g controller"
alias em="ember g model"
alias ecomp="ember g component"
alias clean="clear"
